
import java.awt.Toolkit;
import java.awt.event.WindowEvent;
import java.sql.*;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Redoan
 */
public class showPatientDetail extends javax.swing.JFrame {

    /**
     * Creates new form showPatientDetail
     */
    
    public void close(){
        WindowEvent winClosingEvent = new WindowEvent(this,WindowEvent.WINDOW_CLOS­ING);
        Toolkit.getDefaultToolkit().getSystemEve­ntQueue().postEvent(winClosingEvent);
    }
    
    public showPatientDetail(String s) {
        initComponents();
        try {
            String str="";
             Class.forName("org.sqlite.JDBC");
             Connection conn = DriverManager.getConnection("jdbc:sqlite:patientInfo.sqlite");
             Statement statement = conn.createStatement();
             ResultSet GetData = statement.executeQuery("SELECT * FROM Patient Where Contact= '"+s+"'");
             int i = GetData.getInt("ID");
             String id = "";
             id+=i;
             ID.setText(id);
             name.setText(GetData.getString("Name"));
             address.setText(GetData.getString("Address"));
             cNumber.setText(GetData.getString("Contact"));
             age.setText(GetData.getString("Age"));
             sex.setText(GetData.getString("Sex"));
             mStatus.setText(GetData.getString("MaritalStatus"));
             occupation.setText(GetData.getString("Occupation"));
             if(GetData.getBoolean("Health"))str+="Bad Health\n";
             if(GetData.getBoolean("gumBleed"))str+="Gum Bleed\n";
             if(GetData.getBoolean("tLoose"))str+="Loose Teeth\n";
             if(GetData.getBoolean("chestp"))str+="Chest Pain\n";
             if(GetData.getBoolean("gumd"))str+="Gum Diesease\n";
             if(GetData.getBoolean("badbr"))str+="Bad Breath\n";
             str+="Sensitive to: "+GetData.getString("Sensitivity")+"\n";
             if(GetData.getBoolean("jawpain"))str+="Jaw Pain\n";
             if(GetData.getBoolean("bltend"))str+="Bleading Tendency\n";
             if(GetData.getBoolean("hepatitis"))str+="Hepatitis\n";
             if(GetData.getBoolean("diabetes"))str+="Diabetes\n";
             if(GetData.getBoolean("heartTr"))str+="Heart Trouble\n";
             if(GetData.getBoolean("blPress"))str+="High Blood Pressure\n";
             if(GetData.getBoolean("kidneyD"))str+="Kidney Dieseas\n";
             if(GetData.getBoolean("LiverD"))str+="Liver Dieseas\n";
             if(GetData.getBoolean("LungD"))str+="Lung Dieseas\n";
             if(GetData.getBoolean("Asthma"))str+="Asthma\n";
             if(GetData.getBoolean("rfev"))str+="Rheumatic Fever\n";
             if(GetData.getBoolean("AIDS"))str+="AIDS\n";
             if(GetData.getBoolean("Anemia"))str+="Anemia\n";
             str+="Allergic to: "+GetData.getString("Allergy")+"\n";
             if(sex.getText().equals("Female"))str+="Pregnant: "+GetData.getString("pregnant");
             str+="Medicine taking: "+GetData.getString("med");
             info.setText(str);
             GetData.close();
             statement.close();
             conn.close();
         } 
         catch (Exception e) {
               System.out.println(e);
         }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField1 = new javax.swing.JTextField();
        ID1 = new javax.swing.JLabel();
        Name1 = new javax.swing.JLabel();
        Address1 = new javax.swing.JLabel();
        Contact1 = new javax.swing.JLabel();
        Age1 = new javax.swing.JLabel();
        Sex1 = new javax.swing.JLabel();
        Mstatus1 = new javax.swing.JLabel();
        Occupation1 = new javax.swing.JLabel();
        ID = new javax.swing.JLabel();
        name = new javax.swing.JLabel();
        address = new javax.swing.JLabel();
        cNumber = new javax.swing.JLabel();
        age = new javax.swing.JLabel();
        sex = new javax.swing.JLabel();
        mStatus = new javax.swing.JLabel();
        occupation = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        info = new javax.swing.JTextPane();
        back = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();

        jTextField1.setText("jTextField1");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        ID1.setText("ID");

        Name1.setText("Name");

        Address1.setText("Address");

        Contact1.setText("Contact No.");

        Age1.setText("Age");

        Sex1.setText("Sex");

        Mstatus1.setText("Marital Status");

        Occupation1.setText("Occupation");

        info.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jScrollPane2.setViewportView(info);

        back.setText("Back");
        back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backActionPerformed(evt);
            }
        });

        jButton1.setText("History");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(back, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(Mstatus1)
                                    .addComponent(Sex1)
                                    .addComponent(Age1)
                                    .addComponent(Contact1)
                                    .addComponent(Address1)
                                    .addComponent(Name1)
                                    .addComponent(ID1))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(cNumber)
                                    .addComponent(age)
                                    .addComponent(sex)
                                    .addComponent(mStatus)
                                    .addComponent(address)
                                    .addComponent(name)
                                    .addComponent(ID, javax.swing.GroupLayout.PREFERRED_SIZE, 268, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(Occupation1, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(occupation)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 316, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(37, Short.MAX_VALUE))
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {Address1, Age1, Contact1, ID1, Mstatus1, Name1, Occupation1, Sex1});

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {ID, address, age, cNumber, mStatus, name, occupation, sex});

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {back, jButton1});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 409, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(ID1)
                            .addComponent(ID))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Name1)
                            .addComponent(name))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Address1)
                            .addComponent(address))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Contact1)
                            .addComponent(cNumber))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Age1)
                            .addComponent(age))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Sex1)
                            .addComponent(sex))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Mstatus1)
                            .addComponent(mStatus))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(Occupation1, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(occupation, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(back, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {Address1, Age1, Contact1, ID, ID1, Mstatus1, Name1, Occupation1, Sex1, address, age, back, cNumber, jButton1, mStatus, name, occupation, sex});

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backActionPerformed
        // TODO add your handling code here:
        close();
        new searchAddPatient().setVisible(true);
    }//GEN-LAST:event_backActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        close();
        new history(name.getText()).setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(showPatientDetail.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(showPatientDetail.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(showPatientDetail.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(showPatientDetail.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                String s="";
                new showPatientDetail(s).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Address1;
    private javax.swing.JLabel Age1;
    private javax.swing.JLabel Contact1;
    private javax.swing.JLabel ID;
    private javax.swing.JLabel ID1;
    private javax.swing.JLabel Mstatus1;
    private javax.swing.JLabel Name1;
    private javax.swing.JLabel Occupation1;
    private javax.swing.JLabel Sex1;
    private javax.swing.JLabel address;
    private javax.swing.JLabel age;
    private javax.swing.JButton back;
    private javax.swing.JLabel cNumber;
    private javax.swing.JTextPane info;
    private javax.swing.JButton jButton1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JLabel mStatus;
    private javax.swing.JLabel name;
    private javax.swing.JLabel occupation;
    private javax.swing.JLabel sex;
    // End of variables declaration//GEN-END:variables
}
